name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      - name: Print slug/short variables
        run: |
          echo "Slug variables"
          echo "   ref        : ${{ env.GITHUB_REF_SLUG }}"
          echo "   head ref   : ${{ env.GITHUB_HEAD_REF_SLUG }}"
          echo "   base ref   : ${{ env.GITHUB_BASE_REF_SLUG }}"
          echo "   event ref  : ${{ env.GITHUB_EVENT_REF_SLUG }}"
          echo "   repository : ${{ env.GITHUB_REPOSITORY_SLUG }}"
          echo "Slug URL variables"
          echo "   ref        : ${{ env.GITHUB_REF_SLUG_URL }}"
          echo "   head ref   : ${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
          echo "   base ref   : ${{ env.GITHUB_BASE_REF_SLUG_URL }}"
          echo "   event ref  : ${{ env.GITHUB_EVENT_REF_SLUG_URL }}"
          echo "   repository : ${{ env.GITHUB_REPOSITORY_SLUG_URL }}"
          echo "Short SHA variables"
          echo "   sha        : ${{ env.GITHUB_SHA_SHORT }}"
      - name: dokku application steps via ssh
        uses: docker://evaneos/ssh-action:0.1.0
        with:
          hosts: ${{ secrets.DOKKU_HOST }}
          user: root
          private_key: ${{ secrets.KEY_SSH_DEPLOY }}
          commands: |
            export BASE_BRANCH=${{ env.GITHUB_HEAD_REF_SLUG_URL }}
            sh ./scripts/deploy.sh $BASE_BRANCH

  build:
    name: Deploy
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v1
      - name: Deploy the application
        uses: landmaj/github-action-dokku@master
        with:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          HOST: opentracking.tech
          PROJECT: 'railsapp'
          BRANCH: master
