name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: echo command
      with:
        command: |
          echo "testingg......."
         
  build:
    name: Deploy
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v1
      - name: Deploy the application
        uses: landmaj/github-action-dokku@master
        with:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          HOST: ${{ secrets.DOKKU_HOST }}
          PROJECT: 'railsapp'
          BRANCH: master
